### ISSUE TITLE
 Changelog generator failed

### ISSUE THREAD

**Issue by zillionare** [zillionare/python-project-wizard#1]
while running generate change log step of workflow 'release & publish', it failed to 
generator change log if 0.1.0 doesn't exist.

By default we don't specify since_tag for user, however, the action seems specify 0.1.0
by default, which cause the problem.

the actions:
```
      - name: generate change log
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          # no scineTag here by default. User should add and change at each release
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
          output: CHANGELOG.md
```
call stack:
```
/usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator_tags.rb:138:in `filter_since_tag': Error: can't find tag 0, specified with --since-tag option. (GitHubChangelogGenerator::ChangelogGeneratorError)
	from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator_tags.rb:120:in `get_filtered_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator_tags.rb:15:in `fetch_and_filter_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator.rb:46:in `compound_changelog'
	from /usr/local/bundle/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator.rb:35:in `run'
	from /usr/local/bundle/gems/github_changelog_generator-1.15.0/bin/github_changelog_generator:5:in `<top (required)>'
	from /usr/local/bundle/bin/github_changelog_generator:23:in `load'
	from /usr/local/bundle/bin/github_changelog_generator:23:in `<main>'
Fetching tags... 100/100
```
