### ISSUE TITLE
mkdocs colour toggle option

### ISSUE THREAD

**Issue by ashnair1** [zillionare/python-project-wizard#3]
* Date you used Cookiecutter PyPackage: 15/6/21
* Python version, if any: 3.7
* Operating System: Ubuntu

### Description

Hi I was trying to setup a dark mode light mode toogle as per the [mkdocs documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/) so I basically replaced the following in `mkdocs.yml`

```
   palette:
     primary: light blue
```

with this

```
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
```

However, this doesn't work and the toggle is not displayed. Do you have an idea as to why this happens?
